language: python
python:
    - "2.7"
    - "2.6"
    - "3.5"
    - "3.4"

# command to install dependencies
install:
    - bin/install
    - pip install coveralls

script:
    # command to run tests and coverage
    - bin/cover

after_success:
    # command to run coveralls
    coveralls

services:
  - mongodb